name: Close Issue

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  close-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Needs Reproduction
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'close-issues'
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'M: Needs Reproduction'
          inactive-day: 3
